name: Android Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1) JDK 17 para sdkmanager (exigido pela action)
      - name: Set up JDK 17 (for Android SDK)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android packages
        run: |
          sdkmanager --install \
            "platform-tools" \
            "platforms;android-30" "build-tools;30.0.3" \
            "platforms;android-29" "build-tools;29.0.3"
          yes | sdkmanager --licenses

      - name: Unzip project
        run: unzip -q AppLockerMVP_camuflado.zip -d project

      # 2) Gradle 6.9.4 e JDK 11 para compilar projeto antigo
      - name: Install Gradle 6.9.4 (SDKMAN)
        run: |
          curl -s https://get.sdkman.io | bash
          bash -lc "source $HOME/.sdkman/bin/sdkman-init.sh && sdk install gradle 6.9.4"
          echo 'export PATH="$HOME/.sdkman/candidates/gradle/current/bin:$PATH"' >> $GITHUB_ENV

      - name: Switch to JDK 11 (for Gradle build)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Build Debug APK
        working-directory: project
        run: gradle --no-daemon assembleDebug --stacktrace --info

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: project/app/build/outputs/apk/debug/*.apk
